# Generated by Django 2.0.4 on 2018-11-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artistId', models.AutoField(primary_key=True, serialize=False)),
                ('artistName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('trackId', models.AutoField(primary_key=True, serialize=False)),
                ('trackName', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('genreName', models.CharField(max_length=25)),
                ('releaseDate', models.DateTimeField(auto_now_add=True)),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistdetails.Artists')),
            ],
        ),
    ]
