# Generated by Django 2.0.4 on 2018-11-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='artistId',
            new_name='artist_id',
        ),
    ]
